services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elastic
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  logstash:
      image: logstash:8.0.0
      container_name: log
      environment:
        discovery.seed_hosts: logstash
        LS_JAVA_OPTS: "-Xms512m -Xmx512m"
      volumes:
        - ./logstash/pipeline/logstash-nginx.config:/usr/share/logstash/pipeline/logstash-nginx.config
        - ./logstash/nginx.log:/home/nginx.log
      ports:
        - "5000:5000/tcp"
        - "5000:5000/udp"
        - "5044:5044"
        - "9600:9600"
      depends_on:
        - elasticsearch
      networks:
        - elastic
      command: logstash -f /usr/share/logstash/pipeline/logstash-nginx.config

networks:
  elastic:
    name: elastic-docker-net